XXX: Move Hilla modules from platform
vaadin/hilla pull request #1144
Opened 2023-08-16 07:41 UTC by ZheSun88

this PR is aming to move all hilla related modules to hilla repo, so that hilla can release separately.

- create related modules
  - hilla
  - hilla-bom
  - hilla-dev
  - hilla-react
  - hilla-spring-boot-starter
  - hilla-react-spring-boot-starter

2023-08-16 08:39 UTC, ZheSun88 commented on packages/java/hilla-bom/pom.xml
> +        <slf4j.version>2.0.4</slf4j.version>
this should not need, as slf4j.version is in root pom

2023-08-17 10:28 UTC, ZheSun88 commented
NOTE: 
- need to run `./scripts/generateBoms` to generate the needed hilla-versions.json and hilla-react-versions.json
- 
- seems theme dependencies are needed when excuting build-frontend goal
```
Could not execute build-frontend goal: Error occured during goal execution: Lumo dependency needs to be available on the classpath when using a theme name.Please run Maven with the -e switch (or Gradle with the --stacktrace switch), to learn the full stack trace. -> [Help 1]
```

2023-08-18 09:24 UTC, manolo requested changes

2023-08-18 09:24 UTC, manolo commented on versions.json
I would not maintain this file here, the generateBoms script should download and parse the equivalent from platform to know the entries, and generate it here

2023-08-22 13:29 UTC, ZheSun88 commented on versions.json
updated.

2023-08-29 06:35 UTC, manolo approved these changes

2023-08-29 07:15 UTC, manolo approved these changes

2023-08-29 12:07 UTC, merged