chore: fix Gradle tests failure
vaadin/hilla pull request #1536
Opened 2023-10-17 09:25 UTC by Lodin

2023-10-23 08:13 UTC, taefi requested changes
ATM, I think `single-module-tests` can be just a bare-bone Hilla project with no code in the `src/main` folder (and possibly no heavy package.json content, then no `npm install` and not extra waits for it). Its existence purpose is just for running the `ProductionBuildFunctionalIT` tests from outside of the `single-module` project. There shouldn't be any sort of builds happening for the `single-module-tests` project.

2023-10-23 08:13 UTC, taefi commented on packages/java/tests/gradle/single-module-tests/package.json
> +    "@vaadin/bundles": "24.1.11",
Isn't there a newer version of `bundles` e.g. `24.2.0`?

2023-10-23 08:13 UTC, taefi commented on packages/java/tests/gradle/single-module-tests/package.json
> +      "@hilla/react-form": "2.2.2",
Why not using `2.3.1` already?

2023-10-23 16:03 UTC, platosha commented
Numbers are outdated, but it's OK to update them in another PR.

2023-10-24 08:34 UTC, taefi approved these changes

2023-10-24 08:48 UTC, merged