chore: disable nx cache for all commands in CI
vaadin/hilla pull request #1554
Opened 2023-10-18 13:01 UTC by Lodin

2023-10-18 13:15 UTC, Lodin commented
The check for GitHub action change
https://github.com/vaadin/hilla/actions/runs/6561290978

2023-10-23 11:53 UTC, platosha requested changes

2023-10-23 11:53 UTC, platosha commented on packages/ts/react-form/package.json
> +  "version": "2.3.0-beta.2",
seems not related, let's revert:

```suggestion
  "version": "2.3.0-beta1",
```

2023-10-23 11:53 UTC, platosha commented on packages/ts/react-form/package.json
> +    "@hilla/form": "2.3.0-beta.2"
```suggestion
    "@hilla/form": "2.3.0-beta1"
```

2023-10-23 12:10 UTC, platosha submitted a review, later dismissed

2023-10-23 12:12 UTC, Lodin commented on package.json
>      "build": "sh ./scripts/prepare.sh && nx run-many -t build --all --output-style stream",
Maybe we could replace it with `npm run build` then? It won't affect the caller but will make it easier to remove it later

2023-10-23 12:19 UTC, platosha approved these changes

2023-10-23 12:37 UTC, merged