fix: handle spring csrf as string undefined in meta tags
vaadin/hilla pull request #187
Opened 2022-01-20 13:36 UTC by haijian-vaadin

## Description

When Spring CSRF is disabled, it brings meta tags with string undefined (`'undefined'`) to the index.html page which results in CSRF check malfuction

Fixes #185

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-01-20 14:01 UTC, Lodin requested changes
In common it looks good to me but I would add these small changes.

2022-01-20 20:13 UTC, haijian-vaadin commented on packages/ts/fusion-frontend/src/CsrfUtils.ts
>    const csrfHeader = doc.head.querySelector('meta[name="_csrf_header"]');
This is nice, never knew this, thanks

2022-01-20 20:16 UTC, haijian-vaadin commented on packages/ts/fusion-frontend/src/CsrfUtils.ts
> +    if (value && value.toLocaleLowerCase() !== 'undefined') {
right, it was a typo, autocompleted by the IDE, didn't check carefully, thanks for the catch

2022-01-20 20:18 UTC, haijian-vaadin commented on packages/ts/fusion-frontend/src/CsrfUtils.ts
> +  return undefined;
done, changed the parameter type to `HTMLMetaElement`

2022-01-21 11:34 UTC, Lodin approved these changes

2022-01-21 11:44 UTC, merged