feat: useDataProvider hook (alternative)
vaadin/hilla pull request #1934
Opened 2023-12-22 15:02 UTC by sissbruecker

As an alternative to #1910, this implements a hook that returns a data provider function that can be passed to the grid:
```tsx
const { dataProvider } = useDataProvider(MyListService);

<Grid dataProvider={dataProvider} />
```

It supports the same filter + refresh functionality as the implementation in #1910. In order to make this work, the hook returns a new data provider function reference when the filter changes or refresh is called, which in turn causes grid to reload.

This also requires making some changes to the data provider implementation itself, as it currently requires the grid element for a number of features. In order to remove the grid reference the following changes were necessary:
- The infinite data provider now uses its cached filtered count instead of the grid's cache size for detecting whether to shrink the size or not. Those values should be equivalent, as long as `reset` is called on the data provider whenever the grid should be reloaded or the filter changes.
- Removed the refresh functionality from the data provider itself. Instead, whatever uses the data provider needs to both reset the data provider and trigger a reload of the grid.
- Removed the automatic reload of the grid when the filter changes in the data provider. Instead, whatever uses the data provider needs to both update the filter in the data provider and then trigger a reload of the grid.

The last two points don't concern developers really, as these automatisms are provided by `AutoGrid` and `useDataProvider`.

The hook is currently lacking test coverage which needs to be added to finalize the PR.

2024-01-03 11:35 UTC, taefi commented
Thanks @sissbruecker for this alternative implementation. IMO, both the usage and the implementation are more conventional this way. The refactoring done for removing the dependency of the DataProvider on the Grid makes it more clear and less coupled. I'm in favor of this implementation the one suggested in #1910.

2024-01-09 10:25 UTC, cromoteca approved these changes

2024-01-09 10:29 UTC, cromoteca requested changes
It's weird not to see `useDataProvider` in a TS test

2024-01-15 12:22 UTC, Lodin approved these changes
LGTM

2024-01-29 16:33 UTC, cromoteca approved these changes

2024-01-29 19:37 UTC, merged