refactor: disallow parametrized items in auto menu
vaadin/hilla pull request #2392
Opened 2024-05-06 11:46 UTC by Lodin

Fixes #2378.

2024-05-06 12:39 UTC, taefi commented on packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java
> +                                    || config.getRouteParameters().isEmpty());
I would do this in the following order/style:
1. map clientViewConfigEntry -> clientViewConfigEntry.getValue()
2. filter those satisfying `(config.getRouteParameters() == null || config.getRouteParameters().isEmpty())`
3. filter those satisfying `routeUtil.isRouteAllowed(isUserInRole, isUserAuthenticated, config)`

2024-05-06 12:46 UTC, taefi commented on packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java
> +                                    || config.getRouteParameters().isEmpty());
I would also replace the `.forEach` part with 
```java
.collect(Collectors.toMap(AvailableViewInfo::route, Function.identity()))
```

2024-05-06 12:57 UTC, taefi requested changes

2024-05-06 12:57 UTC, taefi commented on packages/ts/file-router/src/shared/internal.d.ts
> +  views: Readonly<Record<string, ViewConfig>>;
I still wonder whether the views with optional parameters should be available as menus.

2024-05-06 14:27 UTC, taefi requested changes

2024-05-06 14:27 UTC, taefi commented on packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java
> +                                    || config.getRouteParameters().isEmpty());
According to [this](https://github.com/vaadin/hilla/issues/2378#issuecomment-2096002474) comment, the `(config.getRouteParameters() == null || config.getRouteParameters().isEmpty())` which exclude views with parameters (either optional or required) should change to only exclude the routes with required parameters.

2024-05-10 10:18 UTC, platosha requested changes
Let's keep the test fixtures for optional and wildcard parameters, as they are (kind of) supported use cases.

2024-05-10 10:18 UTC, platosha commented on packages/ts/file-router/test/runtime/createMenuItems.spec.ts
>            '/test/empty': {},
```suggestion
          '/test/empty': {},
          '/test/:optional?': { title: 'Optional', params: { ':optional?': RouteParamType.Optional } },
          '/test/*': { title: 'Wildcard', params: { '*': RouteParamType.Wildcard } },
```

2024-05-10 10:18 UTC, platosha commented on packages/ts/file-router/test/runtime/createMenuItems.spec.ts
>          },
```suggestion
        },
        {
          title: 'Optional',
          to: '/test/',
        },
```

2024-05-10 10:18 UTC, platosha commented on packages/ts/file-router/test/runtime/createMenuItems.spec.ts
>          },
```suggestion
        },
        {
          title: 'Wildcard',
          to: '/test/',
        },
```

2024-05-10 10:18 UTC, platosha commented on packages/ts/file-router/test/runtime/createMenuItems.spec.ts
>            '/test/empty': { title: 'empty', menu: { order: 5 } },
```suggestion
          '/test/empty': { title: 'empty', menu: { order: 5 } },
          '/test/:optional?': { title: 'Optional', params: { ':optional?': RouteParamType.Optional } },
          '/a/*': { title: 'Wildcard', params: { '*': RouteParamType.Wildcard } },
```

2024-05-10 10:18 UTC, platosha commented on packages/ts/file-router/test/runtime/createMenuItems.spec.ts
>          },
```suggestion
        },
        {
          title: 'Wildcard',
          to: '/a/',
        },
```

2024-05-10 10:18 UTC, platosha commented on packages/ts/file-router/test/runtime/createMenuItems.spec.ts
>          },
```suggestion
        },
        {
          title: 'Optional',
          to: '/test/',
        },
```

2024-05-20 13:55 UTC, taefi reviewed
From the code changes POV it LGTM!
From the tests POV, I agree with @platosha's comment regarding the support of views with optional params. So, I'm not going to restate those requested changes.

2024-05-20 16:30 UTC, platosha reviewed
Upon a closer look, there is still an issue that the link target path contains optional segments, such as `/:___commentId?` in `/comments/:___commentId?`, for example. Somewhere we need to omit them...

2024-05-20 16:32 UTC, platosha commented
> Upon a closer look, there is still an issue that the link target path contains optional segments, such as `/:___commentId?` in `/comments/:___commentId?`, for example. Somewhere we need to omit them...

addressed in [ba2a093](https://github.com/vaadin/hilla/pull/2392/commits/ba2a09361cf332ad1261b6a65b8b8e4411d8b010)

2024-05-20 16:32 UTC, platosha approved these changes

2024-05-20 16:35 UTC, platosha commented
> From the code changes POV it LGTM! From the tests POV, I agree with @platosha's comment regarding the support of views with optional params. So, I'm not going to restate those requested changes.

I went with the tactic to omit the segments in Java, as it is more convenient there having the parameter info. Now that `createMenuItems` has nothing to do with route parameters, it just uses the path key as is — omitting tests for the use cases is fine.

2024-05-21 06:45 UTC, taefi approved these changes

2024-05-21 07:33 UTC, merged