Use the correct service name
vaadin/hilla pull request #2666
Opened 2024-08-20 13:46 UTC by Legioth

2024-08-20 13:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/hilla?pullRequest=2666) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/hilla?pullRequest=2666) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/hilla?pullRequest=2666) it.</sub>

2024-08-20 14:15 UTC, taefi commented
Funny that since we moved to servlet 5, no one complained about this, so either:

* No one is deploying a war package on a servlet container, or
* The `com.vaadin.hilla.startup.EndpointsValidator` is loaded by Flow automatically since it is implementing `com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer`. 

Then, the question is do we actually need it?
Anyway, this change doesn't harm anyone and should have been applied sooner.

2024-08-20 14:16 UTC, taefi approved these changes

2024-08-21 06:21 UTC, Legioth commented
Should maybe also be cherry picked to 24.4.x?

2024-08-21 07:30 UTC, taefi commented
> Should maybe also be cherry picked to 24.4.x?

At least to 24.4.
2.5 is also using the jakarta namespace.

2025-01-14 17:48 UTC, cromoteca commented
This PR fixes the `EndpointValidator` registration in the servlet container, making it work for the first time. The purpose of this validator is to verify that Hilla endpoints are used in a Spring Boot application. The CSRF tests thus fail because they are not Spring Boot applications, but they do have an endpoint, which is `SignalsHandler`.

There are some possible solutions:
- exclude `SignalsHandler` from the check (this is related to https://github.com/vaadin/hilla/pull/2938 and the need of correctly identify the internal endpoints, as in https://github.com/vaadin/hilla/blob/0638cb8df9b8425de9c73a1388e7138dba35d1e0/packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointController.java#L134-L137).
- log a warning instead of throwing in `EndpointValidator`
- make `EndpointValidator` optional by configuration

2025-01-14 17:49 UTC, cromoteca requested changes
This PR fixes the `EndpointValidator` registration in the servlet container, making it work for the first time. The purpose of this validator is to verify that Hilla endpoints are used in a Spring Boot application. The CSRF tests thus fail because they are not Spring Boot applications, but they do have an endpoint, which is `SignalsHandler`.

There are some possible solutions:
- exclude `SignalsHandler` from the check (this is related to https://github.com/vaadin/hilla/pull/2938 and the need of correctly identify the internal endpoints, as in https://github.com/vaadin/hilla/blob/0638cb8df9b8425de9c73a1388e7138dba35d1e0/packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointController.java#L134-L137).
- log a warning instead of throwing in `EndpointValidator`
- make `EndpointValidator` optional by configuration

2025-01-14 17:58 UTC, cromoteca commented
Some of those changes could not propagate well to some of the cherry-pick target that have been selected for this PR.

2025-01-15 07:18 UTC, cromoteca commented
Also, given that it uses a `ClassFinder` from Flow, it seems to collect *all* classes annotated with `BrowserCallable/Endpoint`, but not all classes will be instantiated and used, so it seems a bit too strong as a check.

2025-01-15 12:14 UTC, taefi commented
I'm in favor of logging a warning instead of throwing in EndpointValidator. A visible enough warning + documentation should be enough.

2025-01-15 12:24 UTC, cromoteca commented
I still see this as a sort of duplicate of https://github.com/vaadin/hilla/pull/2938. While they serve different purposes, the check for the presence of Spring could be added at the same place instead of having to declare a dedicated listener.

2025-01-24 12:47 UTC, cromoteca commented
No longer needed after https://github.com/vaadin/hilla/pull/3167

2025-01-24 12:47 UTC, closed without merging