chore: React 19
vaadin/hilla pull request #2962
Opened 2024-12-06 07:21 UTC by Artur-

2025-02-03 13:19 UTC, Lodin commented
@Artur-, should this PR be closed since #3183 brought both React 19 and pinned dependencies?

2025-02-03 13:25 UTC, Artur- commented
If you have moved to build and test mainly using React 19, then this PR is no longer needed. How do you test with React 18?

2025-02-28 12:47 UTC, platosha commented on .github/workflows/validation.yml
> +  test-react-18:
The manual run to verify this change: https://github.com/vaadin/hilla/actions/runs/13588075190

2025-02-28 13:34 UTC, Lodin requested changes

2025-02-28 13:34 UTC, Lodin commented on packages/ts/generator-plugin-client/package.json
> +    "test:react": "echo 'Not using React, skipping...'",
Let's just remove the command altogether, then Nx will just skip it

2025-02-28 14:30 UTC, merged