fix: clarify TS Docs for better DX
vaadin/hilla pull request #3076
Opened 2024-12-20 12:31 UTC by taefi

Fixes #2936

2025-01-09 16:49 UTC, cromoteca requested changes

2025-01-09 19:29 UTC, taefi commented on packages/ts/react-signals/src/FullStackSignal.ts
> +export interface Operation {
I explained the motivation for this change internally, here: https://vaadin.slack.com/archives/C01EJJNMAC9/p1736339840532009

2025-01-10 08:08 UTC, cromoteca commented on packages/ts/react-signals/src/FullStackSignal.ts
> +export interface Operation {
IDEs can definitely propose `type`s, so it must be a glitch in your own IDE. Or maybe the solution is the `export` you added in `index.ts`. But I'd still like to keep it as a type.

2025-01-13 08:42 UTC, Lodin commented on packages/ts/react-signals/src/FullStackSignal.ts
> +export interface Operation {
According to the definition of `interface` and `type` in the TypeScript system, an `interface` gives the name to the type, while the `type` does not do that. I guess, this is the case here. So, if we want a slightly better intellisense here, the `interface` is preferable; the downside is that you cannot use dynamic type creation like `Readonly<...>` etc.

2025-01-13 17:14 UTC, cromoteca approved these changes

2025-01-13 17:14 UTC, cromoteca commented on packages/ts/react-signals/src/FullStackSignal.ts
> +export interface Operation {
Let's use the interface then.

2025-01-13 18:05 UTC, merged