fix(engine): use Node executable provided from Flow to run the generator
vaadin/hilla pull request #794
Opened 2023-02-27 16:53 UTC by Lodin

Fixes #778.

2023-02-28 08:05 UTC, cromoteca commented
I think that some common code about running external processes could be shared in the https://github.com/vaadin/hilla/tree/main/packages/java/engine-runtime/src/main/java/dev/hilla/internal/runner package.

2023-02-28 11:49 UTC, platosha requested changes

2023-02-28 11:49 UTC, platosha commented on packages/java/engine-runtime/src/main/java/dev/hilla/internal/FlowOptions.java
> +// FIXME: remove after https://github.com/vaadin/flow/issues/16005 is done
The issue was fixed, let’s clean this up.

2023-03-01 09:40 UTC, Lodin commented
@cromoteca, if I understand correctly, you mean that `GeneratorShellRunner` could be moved to `dev.hilla.internal.runner`, right? That sounds like a good idea but there is a problem: `engine-runtime` depends on `engine-core` but not vice versa. Probably, we could move some code to `utils` package or do something similar but I believe it goes outside of the scope of this PR.

2023-03-01 10:03 UTC, cromoteca commented
Yes, I agree to do that as a follow-up

2023-03-01 10:05 UTC, platosha approved these changes

2023-03-01 10:05 UTC, merged