fix(engine-core): rewrite EngineConfiguration to have all path properties OS-agnostic
vaadin/hilla pull request #799
Opened 2023-03-02 22:03 UTC by Lodin

Tests for `engine-core`, `engine-runtime` and `maven-plugin` packages do not run on Windows machine. It happens because the `EngineConfiguration` path properties comparison happens OS-dependently.

This PR fixes the issue by using `java.nio.file.Path` objects instead of strings. The configuration file produced also contains absolute paths instead of relative ones. Also, for tests to be OS-agnostic, a specific test resolver is written.

2023-03-08 08:53 UTC, platosha requested changes
Let us clean up the resources related with the old generator.

2023-03-10 09:08 UTC, cromoteca approved these changes

2023-03-10 10:10 UTC, platosha commented on packages/java/engine-core/src/main/java/dev/hilla/engine/EngineConfiguration.java
> +    public static EngineConfiguration load(File configFile) throws IOException {
Since we don't intent to make the file name configurable, should this be a private method?

2023-03-10 10:10 UTC, platosha commented on packages/java/engine-core/src/main/java/dev/hilla/engine/EngineConfiguration.java
> +    public void store(File file) throws IOException {
How about `storeInDirectory`, similar with `loadDirectory`?

2023-03-10 10:11 UTC, platosha commented
Feel free to ignore my questions here. I'm mostly just wondering if we can make it even cleaner...

2023-03-10 10:11 UTC, platosha approved these changes

2023-03-10 10:25 UTC, Lodin commented on packages/java/engine-core/src/main/java/dev/hilla/engine/EngineConfiguration.java
> +    public void store(File file) throws IOException {
Good catch, thanks!

2023-03-10 12:03 UTC, merged